---
abstract: 'Regional context SMS::Send driver to send messages via eSMS Kerala gateway ( http://api.esms.kerala.gov.in )'
author:
  - 'Indranil Das Gupta <indradg@l2c2.co.in>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: SMS-Send-IN-eSMS
no_index:
  directory:
    - t
    - inc
requires:
  File::Spec: '3.33'
  IO::Socket::SSL: '1.76'
  LWP::UserAgent: '6.04'
  SMS::Send: '0.05'
  Test::Exception: '0.31'
  Test::More: '0.98'
version: '0.01'
